<?= $this->doctype() ?>
<html lang="en">
  <head>
    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <link rel="icon" href="../../../../favicon.ico">

    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Bootstrap core CSS -->
            <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <script src="<?= $this->basePath() ?>/js/jquery-3.1.0.min.js"></script>
    	<script src="<?= $this->basePath() ?>/js/dinamico.js"></script>
    	<script src="<?= $this->basePath() ?>/js/numeral.js"></script>
                
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Banco del Estado</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      

      <div class="container">
        <!-- Example row of columns -->
        <?= $this->content ?>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; <?= date('Y') ?> by José Ignacio Gutiérrez Guzmán. All rights reserved.</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?= $this->inlineScript() ?>
  </body>
</html>
