<table>
	<thead>
	<tr>
		<td colspan="3"><b>Banco del Estado / Bansoft - Software para Bancos</b></td>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td colspan="3">
		Apreciado cliente; con el ánimo de ayudarle a usted a tomar la mejor decisión, sirvase de tomar como referencia este reporte para que pueda se pueda llevar una idea del credito que desea para darle vida a sus sueños.
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="2"><b>Datos del credito y cliente:</b></td>
	</tr>
	<tr>
		<td rowspan="10"><img src="/img/logo.png"></td>
		<td>Nombre tomador de credito:</td>
		<td><?= $this->nombre_completo ?></td>
	</tr>
	<tr>
		<td>Indentificación:</td>
		<td><?= $this->identificacion ?></td>
	</tr>
	<tr>
		<td>Valor solicitado:</td>
		<td>$<?= number_format($this->valor_solicitado,2) ?></td>
	</tr>
	<tr>
		<td>Plazo:</td>
		<td><?= $this->plazo ?> años</td>
	</tr>
	<tr>
		<td>Periodo de gracia:</td>
		<td><?= $this->periodo_gracia ?> años</td>
	</tr>
	<tr>
		<td>Periodo de amortización:</td>
		<td>Cada <?= $this->amortizacion ?> días</td>
	</tr>
	<tr>
		<td colspan="2"><b>Tasas de Interes aplicada:</b></td>
	</tr>
	<tr>
		<td>Efectiva anual:</td>
		<td><?= $this->efectivo_anual ?>%</td>
	</tr>
	<tr>
		<td>Nominal anual:</td>
		<td><?= $this->nominal_anual ?>%</td>
	</tr>
	<tr>
		<td>Periodica:</td>
		<td><?= $this->periodico ?>%</td>
	</tr>
	
	</tbody>
</table>
