<br><br>
<table style="border-style: solid;">
	<thead>
	<tr>
		<td colspan="7"><b><?= $this->tableTittle ?></b></td>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td style="background-color: #e5dada;">Cuota</td>
		<td style="background-color: #e5dada;">Fecha</td>
		<td style="background-color: #e5dada;">Saldo Capital</td>
		<td style="background-color: #e5dada;">Amortización Capital</td>
		<td style="background-color: #e5dada;">Amortización Intereses</td>
		<td style="background-color: #e5dada;">Cuota Fija</td>
		<td style="background-color: #e5dada;">Flujo Caja</td>
	</tr>
	<?= $this->tableContent ?>
	</tbody>
</table>